source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'gujemsiossdk_Example', :exclusive => true do
  pod "gujemsiossdk", :path => "../"
end

target 'gujemsiossdk_Tests', :exclusive => true do
  pod "gujemsiossdk", :path => "../"

  
end
