source 'https://github.com/CocoaPods/Specs.git'

target 'gujemsiossdk_Example', :exclusive => true do
  pod "gujemsiossdk", :path => "../"
  pod 'FBAudienceNetwork'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

end

target 'gujemsiossdk_Tests', :exclusive => true do
  pod "gujemsiossdk", :path => "../"
end

