source 'https://github.com/CocoaPods/Specs.git'

target 'gujemsiossdk_Example', :exclusive => true do
  pod "gujemsiossdk", :path => "../"
end

target 'gujemsiossdk_Tests', :exclusive => true do
  pod "gujemsiossdk", :path => "../"
end

